version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_emprestimo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riscos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_emprestimo
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend_emprestimo
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - .:/app
    env_file:
      - .env

  seed:
    build: .
    command: python app/seed.py
    container_name: seed_emprestimo
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
