services:
  app:
    build: .
    container_name: analise_app
    ports:
      - "8000:8000"   # API FastAPI
      - "8501:8501"   # Frontend Streamlit
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: analise_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riscos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
